version: "3.8"

services:
  app:
    build: .
    container_name: image-host-api-app-1
    restart: always        # yep, don't die silently
    ports:
      - "8000:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=image_host
      - HOST=i.dishis.tech
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8080
      - API_SECRET_KEY=${API_SECRET_KEY}
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: image-host-api-mongo-1
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: image-host-api-tunnel
    command: tunnel run my-tunnel
    restart: always
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - app   # waits for app to be at least created
    networks:
      - default

volumes:
  mongodb_data:
